name: legitdao
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  easy_localization: any
  flutter_web3: ^2.1.9
  url_launcher: ^6.3.1
  webview_flutter: ^4.2.1
  reown_appkit: ^1.2.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.8
  graphview: ^1.2.0
  vector_math: ^2.1.4
  fl_chart: ^0.69.2
  interactive_chart: 0.3.5
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # Assets
  assets:
    - lib/assets/images/
    - lib/localization/

  # Fonts
  fonts:
    - family: HugeIcons
      fonts:
        - asset: lib/assets/fonts/otfs/Font Awesome 6 Free-Regular-400.otf
    - family: SourceSerif
      fonts:
        - asset: lib/assets/fonts/source-serif/ttf/SourceSerif4-Regular.ttf