# defaultContentLanguageInSubdir must be true for this to work.

# French language
[[redirects]]
from = '/fr/**'
to = '/fr/404.html'
status = 404

# Default language must be last.
[[redirects]]
from = '/**'
to = '/en/404.html'
status = 404
